server:
  port: 8085
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: firoze28
    url: jdbc:postgresql://localhost:5432/authdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
application:
  security:
    jwt:
      secret-key: 0ed3e5666e34e213e129671e441fa9f4454ac92ef48740e5811390734f2f6f9a
      expiration: 8640000
